### ISSUE TITLE
Process Analysis

### ISSUE THREAD

**Issue by MadsHeilmann** [audio-engineer/aau-p2-article#16]
I have created a project in Overleaf for the process analysis.

However, should we include the process analysis in the main report as a chapter instead of an appendix? I have seen other reports do it this way. 

A benefit would be that everything text-writing related will all be done using github and issues and projects and such, instead of some of it being in Overleaf and some being through Github.

If not, we can just keep it as a project in Overleaf as we did last time :)

**Comment by audio-engineer** [comment]
But why? Keep everything here

**Comment by Danar435** [comment]
I'm personally fine with both cases. I don't think that it's necessary to include the process analysis as a chapter, as we haven't been called out for it, but if other reports do that, then nothing is stopping us.

As for using GitHub or overleaf, I feel like overleaf works better for a process analysis - something short and quick to write. But that's just me.

**Comment by audio-engineer** [comment]
@MadsHeilmann I don't really see the point in doing it on Overleaf. The only benefit is that we can write the process analysis "fast", which is not really relevant now since we have 2 or 3 months to do it. At the end, we will have to merge the two documents anyway, so what's the point? We did it last time because we were unsure if we would have to submit it as a separate document or append it to the report. Better just keep everything in one place, and insert the process analysis in the appendix.

**Comment by MadsHeilmann** [comment]
I completely agree. Lets do that then :)
